### ISSUE TITLE
use systemd socket activation

### ISSUE THREAD

**Issue by jrwren** [jrwren/etv#5]
https://github.com/coreos/go-systemd/tree/master/examples/activation/httpserver

**Comment by mahditakrim** [comment]
Hi @jrwren,
I want to contribute to this project but I don't know where to start :)
I used to read function comments in the code and try to figure out what's going on, but you don't have any comment yet.
So could you please give me a clue ?

**Comment by jrwren** [comment]
After reading this: http://0pointer.de/blog/projects/inetd.html

I don't think it is a good fit here. I'd rather continue as is.
